coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 2%
        base: auto

flags:
  unittests:
    paths:
      - src/

ignore:
  - "tests/**/*"
  - "**/*.test.ts"
  - "**/*.config.ts"
  - "**/*.config.js"
  - "dist/**/*"
  - "node_modules/**/*"
  - "vitest.setup.ts"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true